#!/usr/bin/env python3
import argparse
import sys
from datetime import date
from pathlib import Path

from http_claim_common import CORE_CHECKS, CORE_TRACES, CORE_VECTORS, ClaimFailure, Runner, render_report, run_checks


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--implementation-name", required=True)
    parser.add_argument("--implementation-version", required=True)
    parser.add_argument("--runner-identity", default="scripts/run-core-http-claim.py")
    parser.add_argument("--output", required=True, help="path to the markdown report to write")
    parser.add_argument("--run-date", default=str(date.today()))
    args = parser.parse_args()

    runner = Runner(args.base_url)

    try:
        results = run_checks(runner, CORE_CHECKS)
    except ClaimFailure as error:
        print(f"claim failure: {error}", file=sys.stderr)
        return 1

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    render_report(
        output_path=output_path,
        title="Core HTTP",
        claim_path="conformance/v1/claims/core-http-claim-seed.md",
        implementation_name=args.implementation_name,
        implementation_version=args.implementation_version,
        runner_identity=args.runner_identity,
        run_date=args.run_date,
        vectors=CORE_VECTORS,
        traces=CORE_TRACES,
        results=results,
        notes=[
            "claimed surface remains `Core` over `HTTP Binding v1`",
            "excluded optional surfaces were not exercised",
            "generated by the standalone external conformance runner",
        ],
    )
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
